language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-snmp.gemspec
- gem install sensu-plugins-snmp-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: HS+M7BPPjnJ7nEfyXJOkrWGDys3DsUVg7Eo6lkPeh536uiEe3WCEA8/cISQ0eS8SFxCQBgSdjQCI9r0mocOAinibiNNpvH1GTBkLAeDbpz0jhpZn1tKkHfiWMvm+TE8NeogxmAZPUpnut45Lt70XKFttU+LXwb/xYHb8PwcnpMM=
  gem: sensu-plugins-snmp
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-snmp
